# expect(charge.order.order_line_items.count).to be 1
# expect(charge.order.order_line_items.first.product).to eq product
# expect(charge.user).to eq user
# expect(user.email).to eq params[:user][:email]
# expect(user.name).to eq params[:user][:name]
# expect(user.phone).to eq params[:user][:phone]
# expect(user.address).to eq params[:user][:address]
# expect(user.city).to eq params[:user][:city]
# expect(user.state).to eq params[:user][:state]
# expect(user.zip).to eq params[:user][:zip]
# expect(user.stripe_token).not_to eq nil
